Fix: Use GIT_LFS_SKIP_SMUDGE during build
Since we use not actual Blende repo but a mirror, it lacks LFS objects that Blender seems to have since 4.5.0, which leads to errors during checkout.

Example error:
```
Changing to the target git ref ...
+ cd /home/runner/work/fake-bpy-module/fake-bpy-module/./blender
++ get_remote_git_ref v4.5.0
++ local ref=v4.5.0
+++ git ls-remote origin v4.5.0
+++ head -n 1
+++ cut -f1
++ local remote_ref=8cb6b388974a817afedf1317ce26f0c75aa5f181
++ '[' -z 8cb6b388974a817afedf1317ce26f0c75aa5f181 ']'
++ echo 8cb6b388974a817afedf1317ce26f0c75aa5f181
+ remote_git_ref=8cb6b388974a817afedf1317ce26f0c75aa5f181
+ git fetch --depth 1 origin 8cb6b388974a817afedf1317ce26f0c75aa5f181
From https://github.com/blender/blender
 * branch              8cb6b388974a817afedf1317ce26f0c75aa5f181 -> FETCH_HEAD
+ git checkout -f 8cb6b388974a817afedf1317ce26f0c75aa5f181
Downloading assets/brushes/essentials_brushes-mesh_sculpt.blend (2.6 MB)
Error downloading object: assets/brushes/essentials_brushes-mesh_sculpt.blend (b0357ed): Smudge error: Error downloading assets/brushes/essentials_brushes-mesh_sculpt.blend (b0357ed7ac2b362ec3d37caf638539a7cf1a0625306c5cbb7f840640761e602d): [b0357ed7ac2b362ec3d37caf638539a7cf1a0625306c5cbb7f840640761e602d] Object does not exist on the server: [404] Object does not exist on the server

Errors logged to '/home/runner/work/fake-bpy-module/fake-bpy-module/blender/.git/lfs/logs/20251031T165230.367767817.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: assets/brushes/essentials_brushes-mesh_sculpt.blend: smudge filter lfs failed
```